# Generated by Django 2.0.2 on 2018-02-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_article', models.IntegerField()),
                ('title', models.TextField(default='title')),
                ('text', models.TextField(default='text')),
                ('time', models.IntegerField(default=0)),
                ('descendants', models.CharField(max_length=70)),
                ('by', models.CharField(max_length=70)),
                ('kids', models.TextField(default='kids')),
                ('type', models.CharField(max_length=70)),
                ('score', models.TextField(default='sscore')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Represent url of category', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.Category'),
        ),
    ]
